name: tce-conf
version: '1.5'
synopsis: Very simple config file reading
description: This package contains modules for runtime reading of very simple config files of the `key=value` style or as a Haskell data structure to be deserialized with `Read`. The modules support files with blank lines and simple single-line comments, but nothing else.
license: ISC
author: Dino Morelli
maintainer: Dino Morelli <dino@ui3.info>
category: Configuration
extra-source-files:
- changelog.md
- README.md
- stack.yaml

github: dino-/tce-conf

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- BangPatterns
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies


dependencies:

- base >=3 && <5


library:
  source-dirs: src/lib
  dependencies:
  - containers


executables:

  KVConf-example:
    main: KVConf-example.hs
    source-dirs: src/app
    dependencies:
    - containers
    - tce-conf

  ReadConf-example:
    main: ReadConf-example.hs
    source-dirs: src/app
    dependencies:
    - containers
    - tce-conf


tests:

  test-main:
    main: test-main.hs
    source-dirs:
    - src/tests
    dependencies:
    - containers
    - HUnit
    - tce-conf
